name: Create release
description: 'Create a release and upload assets to it'
inputs:
  release_files:
    description: 'Files to include in the release'
    required: true
    default: 'archive'
  tag_name:
    description: 'The name of the tag'
    required: true
  release_name:
    description: 'The name of the release'
    required: true  
  OCI_TOKEN:
    description: 'The token to use for the release'
    required: true  
  
runs:
    using: composite
    steps:
    
      - name: Create Zip
        shell: bash
        run: |
          zip -r MY_INTEGRATION_FILE.zip ./${{ inputs.release_files }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ inputs.OCI_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }
          release_name: ${{ inputs.release_name }}
          draft: false
          prerelease: false

      - name: Upoad Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ inputs.OCI_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MY_INTEGRATION_FILE.zip
          asset_name: MY_INTEGRATION_FILE.zip
          asset_content_type: application/zip
