name: Create release
on:
  workflow_dispatch:
    inputs:
      release_files:
        description: 'Files to include in the release'
        required: true
        default: 'archive'
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Create release
      uses: ./actions/create-custom-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:       
        release_files: ${{ github.event.inputs.release_files }}
        tag_name: 1.0.v${{ github.run_number }}
        release_name: 1.0.v${{ github.run_number }}
