name: Create custom release
on:
  workflow_dispatch:
    inputs:
        RELEASE_TAG:
            description: 'Release tag'
            required: true
            default: 'latest'
        file_name:
            description: 'File name'
            required: true
            default: 'file1.md'
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Download Release Asset
      id: download_release_asset
      uses: i3h/download-release-asset@v1
      with:
        owner: im-sandbox-phanirb
        repo: DD-oracle-2024
        tag: ${{ inputs.RELEASE_TAG }}
        file: MY_INTEGRATION_FILE.zip
        path: .
        token: ${{ secrets.OCI_TOKEN }}

    - name: Unzip Artifact
      run: |
        unzip -o MY_INTEGRATION_FILE.zip

    - name: check release asset
      run: |
        ls -la
        cd archive
        ls -la
        cd ..
        mkdir custom_release
        cp archive/${{ inputs.file_name }} custom_release
        ls -la custom_release
        echo "Custom release created"

    - name: Call create release workflow
      uses: actions/github-script@main
      with:
        script: | 
          github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'create_release.yml',
                  ref: 'main',
                  inputs: {
                    release_files: 'custom_release'                 
                  }
                });   
    
